### ISSUE TITLE
500 error on first launch

### ISSUE THREAD

**Issue by alxrsngrtn** [jlevers/sunrise-strike-circles#16]
### Steps to reproduce: 
1.  Fresh install according to setup instructions (assumed a DB configuration according to settings/common.py
2. `./manage.py runserver`
3. Went to `localhost:8000` in my browser

### Result: 
Environment:

Request Method: GET
Request URL: http://localhost:8000/strike-circle/

Django Version: 3.0.2
Python Version: 3.7.6
Installed Applications:
['strikecircle',
 'localflavor',
 'phonenumber_field',
 'sass_processor',
 'bulma',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/Users/alxrsngrtn/Github/sunrise-strike-circles/strikecircle/views.py", line 98, in get_context_data
    sc = StrikeCircle.objects.get(user__id=self.request.user.id)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/anaconda3/envs/sunrise-strike-circles/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name

Exception Type: DoesNotExist at /strike-circle/
Exception Value: StrikeCircle matching query does not exist.

**Comment by alxrsngrtn** [comment]
Solution: Go to `localhost:8000/users/signup` and create a first user and strike circle. Then login as that user.

**Comment by jlevers** [comment]
Just for posterity, this was a database config issue. Solved on the phone.

If you create a Django superuser, either a) manually create a `StrikeCircle` and set its `user` field to your superuser, or go to `/users/signup`, go through the signup form, and from then on log into the site as the user you create via that form.

`User`s and `StrikeCircle`s are directly connected, so when you log in as a superuser who doesn't have a `StrikeCircle`, it breaks the site.
